### ISSUE TITLE
Add a parse method to the CLIKommander class that allows to run the cli-app

### ISSUE THREAD

**Issue by iolave** [iolave/swift-kommander#14]
## Summary
swift-kommander does not currently have a method that allows to parse the `argv`, `argc` input from it's execution and thus, it's not able to run any given action.

**Comment by iolave** [comment]
To be able to do this there are some tasks that has to be finished first:

- [ ] #6 (dependency declared on 2023-05-02)
- [ ] #4 (dependency declared on 2023-05-02)
- [ ] #7 (dependency declared on 2023-05-02)
- [ ] #3 (dependency declared on 2023-05-02)

**Comment by iolave** [comment]
Moved to blocked as not every related issue is finished.

**Comment by iolave** [comment]
Moved to `In Progress` cuz of #6 is in `PR` status and will allow to keep working this.

**Comment by iolave** [comment]
#3 is in `PR` status.
